name: lecturas_usiap_movil
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  path:
  mobile_scanner:
  firebase_core:
  cloud_firestore:
  connectivity_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
